local BrannfredToggleButton = CreateFrame("Button", "BrannfredToggleButton", UIParent)
BrannfredToggleButton:RegisterForClicks("AnyUp")
BrannfredToggleButton:SetScript("OnClick", function()
    Brannfred:OnToggleFrame()
end)
